# 开始URL列表
start_urls:
  - "https://blog.bling.moe/"

# 优先级规则，优先抓取匹配的URL，避免浪费时间在无关页面
priority_rules:
  - pattern: ".*post.*"
    priority: 10
  # - pattern: ".*page.*"
  #   priority: 5

# 数据提取规则，使用CSS选择器或XPath表达式
data_extraction:
  title: "css:title"
  published_date: "css:time.post-date"
  modified_date: "css:span.post-moddate"
  author: "css:span.post-author"

# 域名白名单，避免抓取无关页面
allowed_domains:
  - "blog.bling.moe"

# 默认日志在log/crwal.log
save_dir: "data"

# 每条数据保存为一个json文件
save_as: "json"

# 日志级别，DEBUG, INFO, WARNING, ERROR
log_level: "INFO"

# 单次请求超时时间（秒）
fetch_timeout: 10

# 排除文件类型
exclude_patterns:
  - ".*\\.(xml|json)$"
  - ".*\\.(jpe?g|png|gif|bmp|svg|ico|webp)$"
  - ".*\\.(pdf|docx?|xlsx?|pptx?)$"
  - ".*\\.(zip|rar|7z|tar|gz)$"
  - ".*\\.(mp3|wav|ogg|mp4|avi|mov|mkv)$"
  - ".*\\.(exe|dmg|apk|iso)$"

